"""Customizable colors used in the Shell
"""

from colorama import Fore, Back, Style


# Help Command Colors

HELP_USAGE_STYLE = Style.BRIGHT
HELP_USAGE_FORE = Fore.GREEN

HELP_TEXT_FORE = Style.DIM

HELP_OPTION_DESCRIPTION_STYLE = Style.DIM
HELP_OPTION_NAME_STYLE = Fore.YELLOW
HELP_OPTION_HEADER_FORE = Fore.WHITE
HELP_OPTION_HEADER_BACK = Back.MAGENTA
HELP_OPTION_HEADER_STYLE = Style.BRIGHT

HELP_ARGUMENT_DESCRIPTION_STYLE = Style.DIM
HELP_ARGUMENT_NAME_STYLE = Fore.YELLOW + Style.BRIGHT
HELP_ARGUMENT_CLASS_STYLE = Fore.CYAN
HELP_ARGUMENT_ARROW_STYLE = Fore.RED
HELP_ARGUMENT_HEADER_FORE = Fore.WHITE
HELP_ARGUMENT_HEADER_BACK = Back.RED
HELP_ARGUMENT_HEADER_STYLE = Style.BRIGHT

HELP_COMMAND_DESCRIPTION_STYLE = Style.DIM
HELP_COMMAND_NAME_STYLE = Fore.YELLOW
HELP_COMMAND_HEADER_FORE = Fore.WHITE
HELP_COMMAND_HEADER_BACK = Back.BLUE
HELP_COMMAND_HEADER_STYLE = Style.BRIGHT


# Exception Colors

USAGE_ERROR_STYLE = Fore.RED

CLICK_ERROR_STYLE = Fore.RED

UNEXPECTED_ERROR_TEXT_STYLE = Fore.YELLOW

PYTHON_ERROR_HEADER_FORE = Fore.WHITE
PYTHON_ERROR_HEADER_BACK = Back.RED
PYTHON_ERROR_HEADER_STYLE = Style.BRIGHT
PYTHON_STACKTRACE_STYLE = Style.DIM


# CMD Colors

COMMAND_NOT_FOUND_TEXT_STYLE = Style.DIM
COMMAND_NOT_FOUND_TEXT_FORE = Fore.YELLOW

SUGGEST_TEXT_STYLE = Style.BRIGHT
SUGGEST_TEXT_COLOR = Fore.CYAN
SUGGEST_ITEMS_STYLE = Fore.YELLOW


# Completion Colors

COMPLETION_COMMAND_NAME = 'ansiblue'
COMPLETION_COMMAND_DESCRIPTION = 'fg=\"#cc66ff\"'
COMPLETION_ROOT_COMMAND_NAME = 'ansiblue'
COMPLETION_ROOT_COMMAND_DESCRIPTION = 'fg=\"#cc66ff\"'

COMPLETION_CHOICE_DEFAULT = 'ansiblack'
COMPLETION_CHOICE_BOOLEAN_TRUE = 'ansigreen'
COMPLETION_CHOICE_BOOLEAN_FALSE = 'ansired'

COMPLETION_OPTION_NAME = 'ansibrightmagenta'
COMPLETION_OPTION_DESCRIPTION = 'fg=\"#cc66ff\"'

COMPLETION_ARGUMENT_NAME = 'ansired'
COMPLETION_ARGUMENT_DESCRIPTION = 'fg=\"#cc66ff\"'


# Base Shell Command Colors

SHELL_HISTORY_CLEARED_STYLE = Style.DIM
SHELL_HISTORY_CLEARED_TRUE = Fore.GREEN
SHELL_HISTORY_CLEARED_FALSE = Fore.RED